jari_jari=float(input())
tinggi_bejana=float(input())
phi=float(3.14285)
volume= phi* jari_jari*jari_jari*tinggi_bejana
luas=2*phi*jari_jari*(jari_jari+tinggi_bejana)
keliling=2*phi*jari_jari
print("Volume = {:.2f}".format (volume))
print("Luas = {:.2f}" .format(luas))
print("Keliling = {:.2f}".format(keliling))
